### ISSUE TITLE
Interesting dip in # bee records

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/global-bee-interaction-data#2]
@jhpoelen I am having fun looking at some trends in bee records from GloBI. At 11-17-2021 there was a significant dip in the number of bee records. Any idea why this happened? I would expect some duplication was removed.

Date | Total bee records | Andrenidae | Apidae | Colletidae | Halictidae | Megachilidae | Melittidae | Stenotritidae
-- | -- | -- | -- | -- | -- | -- | -- | --
07-17-2020 | 306,369 | 73,463 | 106,222 | 20,821 | 58,880 | 44,449 | 2,511 | 23
01-24-2021 | 335,562 | 77,824 | 120,919 | 21,376 | 63,945 | 48,856 | 2,624 | 18
11-17-2021 | 251,695 | 25,535 | 134,517 | 10,568 | 43,070 | 37,001 | 995 | 9
06-01-2022 | 364,834 | 78,016 | 144,827 | 20,409 | 64,054 | 54,516 | 2,994 | 18
11-07-2022 | 429,308 | 84,172 | 171,378 | 30,792 | 79,155 | 61,391 | 2,396 | 24

![Screen Shot 2022-11-09 at 7 37 12 AM](https://user-images.githubusercontent.com/1044474/200873842-605dd4b6-d33e-43a1-b89d-70776d755cca.png)

**Comment by jhpoelen** [comment]
Glad to hear you are having fun with the over-time progressions on your bee interaction dataset.

This dip is definitely interesting! A breakdown by namespace / data source may offer some insights. . .

**Comment by jhpoelen** [comment]
@seltmann I just noticed this open 2022 issue related to a suspicious dip in bee interaction records. Would you like to better understand the dip, or close the issue and move on?

**Comment by seltmann** [comment]
we can close this issue
