### ISSUE TITLE
update taxonomic alignment scripts to use verbatim names against big bee taxonomic name mapping

### ISSUE THREAD

**Issue by jhpoelen** [Big-Bee-Network/global-bee-interaction-data#9]
as discussed with @seltmann, we'd like to:

1. use verbatim names from GloBI interaction records 
2. write script to use specific Nomer matcher to generate name matching list
3. publish the bee interaction database name alignment list
4. use bee interaction database name alignment list to produce//publish interpreted bee interactions 

So, instead of relying on an interpreted interaction datasets using the GloBI taxon graph, we'd like to have more control of the taxonomic interpretation by using a big bee specific name alignment method.

**Comment by seltmann** [comment]
related to [https://github.com/Big-Bee-Network/select-bee-interactions.sh/tree/main](https://github.com/Big-Bee-Network/select-bee-interactions.sh/tree/main) and solution described at [https://www.globalbioticinteractions.org/2024/06/07/bees-only-please](https://www.globalbioticinteractions.org/2024/06/07/bees-only-please)
